version: '2'
services:
  product-svc:
    build:
      context: ./product-svc/
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./product-svc/src:/home/node/app/src
      - ./product-svc/nodemon.json:/home/node/app/nodemon.json
    container_name: product-svc
    expose:
      - '5400'
    ports:
      - '5400:5400'
    command: npm run dev

services:
  db:
    image: mariadb
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: classmate123.
      MYSQL_DATABASE: Products_Svc_DB
      MYSQL_USER: Products_Svc_User
      MYSQL_PASSWORD: classmate123.
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
